// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[slug].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/api/[land].ts";
import * as $4 from "./routes/api/dev.ts";
import * as $5 from "./routes/api/getProductByLink.ts";
import * as $6 from "./routes/api/getStoreById.ts";
import * as $7 from "./routes/api/searchVector.ts";
import * as $8 from "./routes/api/send.ts";
import * as $9 from "./routes/api/sendz.ts";
import * as $10 from "./routes/api/test.ts";
import * as $11 from "./routes/index.tsx";
import * as $12 from "./routes/mojo/admin.tsx";
import * as $13 from "./routes/mojo/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/mojo/Llists.tsx";
import * as $$2 from "./islands/mojo/admin.tsx";

const manifest = {
  routes: {
    "./routes/[slug].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/api/[land].ts": $3,
    "./routes/api/dev.ts": $4,
    "./routes/api/getProductByLink.ts": $5,
    "./routes/api/getStoreById.ts": $6,
    "./routes/api/searchVector.ts": $7,
    "./routes/api/send.ts": $8,
    "./routes/api/sendz.ts": $9,
    "./routes/api/test.ts": $10,
    "./routes/index.tsx": $11,
    "./routes/mojo/admin.tsx": $12,
    "./routes/mojo/index.tsx": $13,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/mojo/Llists.tsx": $$1,
    "./islands/mojo/admin.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
