create table
  public.users (
    id bigint generated by default as identity,
    username text not null,
    email text not null,
    password text not null,
    mobile text not null,
    uuid uuid null default gen_random_uuid (),
    token text null,
    avatar text null,
    status text null default ''::text,
    is_active boolean null default true,
    bio text null,
    constraint users_pkey primary key (id),
    constraint unique_email unique (email),
    constraint unique_username unique (username),
    constraint users_users_user_id_key unique (id)
  ) tablespace pg_default;
