create table
  public.role (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    name text null,
    constraint role_pkey primary key (id)
  ) tablespace pg_default;