create table
  public.lookups (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    udid uuid null default gen_random_uuid (),
    key text null,
    label text null,
    value text null,
    status text null,
    is_active boolean null default true,
    type text null,
    name text null,
    text text null,
    json jsonb null,
    constraint lockups_pkey primary key (id)
  ) tablespace pg_default;